create extension if not exists "pgcrypto";

create type public.dashboard_role as enum ('owner', 'hr');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) > 0),
  role public.dashboard_role not null default 'hr',
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.locations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) > 0),
  city text not null check (char_length(trim(city)) > 0),
  state text not null check (char_length(trim(state)) > 0),
  created_at timestamptz not null default timezone('utc', now()),
  unique (name, city, state)
);

create table public.employees (
  id uuid primary key default gen_random_uuid(),
  employee_code text not null unique,
  full_name text not null check (char_length(trim(full_name)) > 0),
  email text not null,
  phone text not null,
  designation text not null,
  department text not null,
  location_id uuid not null references public.locations(id) on delete restrict,
  joining_date date not null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index employees_email_unique on public.employees (lower(email));
create index employees_name_index on public.employees (lower(full_name));
create index employees_location_index on public.employees (location_id);
create index employees_status_index on public.employees (status);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger employees_set_updated_at
before update on public.employees
for each row execute function public.set_updated_at();

create or replace function public.protect_employee_audit_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
begin
  if tg_op = 'INSERT' then
    if actor is not null then
      new.id := gen_random_uuid();
      new.created_at := timezone('utc', now());
      new.updated_at := timezone('utc', now());
      new.created_by := actor;
      new.updated_by := actor;
    end if;
  else
    if new.id is distinct from old.id
      or new.created_by is distinct from old.created_by
      or new.created_at is distinct from old.created_at then
      raise exception 'Employee audit fields are immutable';
    end if;

    if actor is not null then
      new.updated_at := timezone('utc', now());
      new.updated_by := actor;
    end if;
  end if;

  return new;
end;
$$;

create trigger employees_protect_audit_fields
before insert or update on public.employees
for each row execute function public.protect_employee_audit_fields();

create or replace function public.is_dashboard_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('owner', 'hr')
      and status = 'active'
  );
$$;

create or replace function public.is_dashboard_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'owner'
      and status = 'active'
  );
$$;

create or replace function public.record_employee_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
    values (auth.uid(), 'created', 'employee', new.id, jsonb_build_object('employee_code', new.employee_code));
  elsif tg_op = 'UPDATE' then
    insert into public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
    values (auth.uid(), 'updated', 'employee', new.id, jsonb_build_object('employee_code', new.employee_code));
  else
    insert into public.audit_logs (actor_id, action, entity_type, entity_id, metadata)
    values (auth.uid(), 'deleted', 'employee', old.id, jsonb_build_object('employee_code', old.employee_code));
  end if;
  return new;
end;
$$;

create trigger employees_record_audit
after insert or update or delete on public.employees
for each row execute function public.record_employee_audit();

alter table public.profiles enable row level security;
alter table public.locations enable row level security;
alter table public.employees enable row level security;
alter table public.audit_logs enable row level security;

create policy profiles_select_dashboard on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_dashboard_user());

create policy locations_select_dashboard on public.locations
for select to authenticated
using (public.is_dashboard_user());

create policy locations_insert_dashboard on public.locations
for insert to authenticated
with check (public.is_dashboard_user());

create policy locations_update_dashboard on public.locations
for update to authenticated
using (public.is_dashboard_user())
with check (public.is_dashboard_user());

create policy locations_delete_dashboard on public.locations
for delete to authenticated
using (public.is_dashboard_user());

create policy employees_select_dashboard on public.employees
for select to authenticated
using (public.is_dashboard_user());

create policy employees_insert_dashboard on public.employees
for insert to authenticated
with check (public.is_dashboard_user() and created_by = auth.uid());

create policy employees_update_dashboard on public.employees
for update to authenticated
using (public.is_dashboard_user())
with check (public.is_dashboard_user() and updated_by = auth.uid());

create policy employees_delete_owner on public.employees
for delete to authenticated
using (public.is_dashboard_owner());

create policy audit_logs_select_dashboard on public.audit_logs
for select to authenticated
using (public.is_dashboard_user());

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.locations, public.employees to authenticated;
grant select on public.profiles to authenticated;
grant select on public.audit_logs to authenticated;

insert into public.locations (name, city, state)
values
  ('Gandhidham', 'Gandhidham', 'Gujarat'),
  ('Jamnagar', 'Jamnagar', 'Gujarat'),
  ('Beohari', 'Shahdol', 'Madhya Pradesh'),
  ('Ramnagar', 'Maihar', 'Madhya Pradesh'),
  ('Bhopal', 'Bhopal', 'Madhya Pradesh'),
  ('Jabalpur', 'Jabalpur', 'Madhya Pradesh')
on conflict (name, city, state) do nothing;
